In [3]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
sal=np.array(a)
print(sal)
print("dimension of the array are",sal.ndim)
print("shape of the array is ",sal.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension of the array are 2
shape of the array is  (3, 3)


In [18]:
arr=np.zeros(5)
#print("one dimesntional array is ",x)
arr
x=np.zeros((2,3))
print("the 2D array is\n",x)

the 2D array is
 [[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [25]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
sal=np.zeros(5)
sal

array([0., 0., 0., 0., 0.])

In [37]:
#demonstrating the numpy function eye
sal=np.eye(5)
sal

sal=np.eye(4,5)
sal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [39]:
sal=np.diag([1,2,3,4])
sal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [59]:
sal=np.diag([1,2,3,4,5,6,7,8,9,10])
sal
np.diag(sal)

sal=np.random.randint(1,20,5)
sal=np.random.randint(1,20,4)
sal
sal=np.random.rand(10)
sal
sal=np.random.rand(100)
sal

array([0.93573474, 0.25121242, 0.206649  , 0.59130946, 0.65678967,
       0.22078253, 0.40480219, 0.73207394, 0.21052249, 0.45118748,
       0.75587005, 0.86551819, 0.16667282, 0.46310334, 0.69963095,
       0.53823268, 0.16527155, 0.60739885, 0.93550563, 0.89189008,
       0.02349061, 0.10197969, 0.66286534, 0.9758888 , 0.01891025,
       0.90195683, 0.59155007, 0.64415492, 0.61012739, 0.30698755,
       0.86260297, 0.58361335, 0.22322149, 0.46250208, 0.1836506 ,
       0.03803027, 0.32657673, 0.58180031, 0.4966576 , 0.37646967,
       0.61688965, 0.43998286, 0.72733384, 0.85117745, 0.70026999,
       0.81869168, 0.78958044, 0.77218862, 0.40727506, 0.79028983,
       0.82512994, 0.74787271, 0.52510289, 0.15088168, 0.55913717,
       0.10659566, 0.33120188, 0.38192224, 0.48705142, 0.49507613,
       0.04830181, 0.71121658, 0.06311678, 0.04615254, 0.90063126,
       0.13352124, 0.90430856, 0.66772183, 0.92640904, 0.43624796,
       0.28360062, 0.75458793, 0.82708516, 0.4256167 , 0.45695

In [64]:
sal=np.random.rand(4,2)
sal
sal=np.random.randn(4)
sal


array([-2.31839179,  0.10563354,  0.87414077, -0.23396713])

In [87]:
import numpy as np
list=[]
size=int(input("Enter the size of the array\n"))
for i in range(size):
    val=int(input("Enter values \n"))
    list.append(val)
print(list)
sal=np.array(list)
print(sal)
for i in range(sal.size):
    print("list",[i],"=",sal[i])
salman=list[2:5]
print(salman)

Enter the size of the array
5
Enter values 
10
Enter values 
20
Enter values 
30
Enter values 
40
Enter values 
50
[10, 20, 30, 40, 50]
[10 20 30 40 50]
list [0] = 10
list [1] = 20
list [2] = 30
list [3] = 40
list [4] = 50
[30, 40, 50]


In [3]:
import numpy as np
sal=np.random.randint(1,50,12)
sal
sal.shape
sal
arr=sal.reshape(4,3)
print(arr)
print("after reshaping",arr.ndim)

[[41 30  4]
 [ 6  1  6]
 [ 7 35 29]
 [47 36  9]]
after reshaping 2


In [18]:
sal=np.random.randint(1,60,20)
sal
sal.shape
array=sal.reshape(4,5)
print(array)
array=sal.reshape(5,4)
print(array)

#convert a 1d array to 2d and 3d
array=np.random.randint(1,100,12)
array
array.shape
x=array.reshape(2,2,3)
x

[[56 33  8 59 13]
 [17 59 29  9 26]
 [ 2 35 13 43 35]
 [10  8 25  6 42]]
[[56 33  8 59]
 [13 17 59 29]
 [ 9 26  2 35]
 [13 43 35 10]
 [ 8 25  6 42]]


array([[[40, 59, 12],
        [31, 15, 46]],

       [[13, 28, 72],
        [53, 22, 80]]])

In [1]:
sal=np.random.randint(1,50,12)
sal.shape
array=sal.reshape(4,-1)
array
array=sal.reshape(-2,)

NameError: name 'np' is not defined

In [5]:
import numpy as np
np.random.seed(12)
sal=np.random.randint(1,100,10)
sal
sal.size

10

In [22]:
import numpy as np
list=[]
row=int(input("Enter the no of rows"))
col=int(input("Enter the no of coloumns"))
for i in range(row):
    a=[]
#     val1=int(input("Enter value pls\n"))
#     list.append(val1)
    for j in range(col):
        val2=int(input("Enter values\n"))
        a.append(val2)
    list.append(a)
arr=np.array(list)
for i in range(row):
    for j in range(col):
        print(arr[i][j],end=" ")
    print()
print(type(arr))

Enter the no of rows4
Enter the no of coloumns3
Enter values
1
Enter values
2
Enter values
3
Enter values
4
Enter values
5
Enter values
6
Enter values
7
Enter values
8
Enter values
9
Enter values
10
Enter values
11
Enter values
12
1 2 3 
4 5 6 
7 8 9 
10 11 12 
<class 'numpy.ndarray'>


In [ ]:
import pandas as pd
sal=pd.read_csv("C:\\Users\\salma\\OneDrive\\Documents\\data_set.csv")
sal
sal['event',"Sunny"]